var today = new Date();
var date = today.getDate();
var month = today.getMonth();
var realMonth = month + 1;
var year = today.getFullYear();
var hour = today.getHours();
var minute = today.getMinutes();
document.open();
document.getElementById("time");
document.write(realMonth + "/" + date + "/" + year + "  |  " + hour + ":" + minute);
document.close();